fasta:
    none
long_reads:
    none
long_read_type:
    ont
medaka_model:
    r941_min_hac_g507
short_reads_1:
    none
short_reads_2:
    none
min_contig_size:
    1500
min_bin_size:
    200000
max_threads:
    8
pplacer_threads:
    8
max_memory:
    250
genome_size:
    5000000
reference_filter:
    none
strain_analysis:
    False
unassembled_long:
    none
mags:
    none
mag_directory:
    none
mag_extension:
    none
instrain_params:
    {}
profile_read_list:
    none
min_long_read_length:
    500
keep_percent:
    99
min_mean_q:
    40
guppy_model:
    r941_min_high_g360
gtdbtk_folder:
    none
busco_folder:
    none
checkm2_db_folder:
    none
eggnog_folder:
    none
singlem_metapackage:
    none
virsorter_data:
    none
email:
    somename@email.co